// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvhuauNrTcnvO2_-xn98NMAKwfaSZfT8',
    appId: '1:390654080778:web:4f14d467444dba792cacf3',
    messagingSenderId: '390654080778',
    projectId: 'reciclareapp-8fb25',
    authDomain: 'reciclareapp-8fb25.firebaseapp.com',
    storageBucket: 'reciclareapp-8fb25.firebasestorage.app',
    measurementId: 'G-N18EEL9NDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQMGLSTzbfswME-c38jGcCXungEKdIes',
    appId: '1:390654080778:android:f27d2f0271a58b8d2cacf3',
    messagingSenderId: '390654080778',
    projectId: 'reciclareapp-8fb25',
    storageBucket: 'reciclareapp-8fb25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYKoNpvcumAlPevfa1JmNWsy4GhPW4fI',
    appId: '1:390654080778:ios:144ec5f2131e5e1b2cacf3',
    messagingSenderId: '390654080778',
    projectId: 'reciclareapp-8fb25',
    storageBucket: 'reciclareapp-8fb25.firebasestorage.app',
    iosBundleId: 'com.example.garbageselection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYKoNpvcumAlPevfa1JmNWsy4GhPW4fI',
    appId: '1:390654080778:ios:144ec5f2131e5e1b2cacf3',
    messagingSenderId: '390654080778',
    projectId: 'reciclareapp-8fb25',
    storageBucket: 'reciclareapp-8fb25.firebasestorage.app',
    iosBundleId: 'com.example.garbageselection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsvhuauNrTcnvO2_-xn98NMAKwfaSZfT8',
    appId: '1:390654080778:web:2b82609f417f504d2cacf3',
    messagingSenderId: '390654080778',
    projectId: 'reciclareapp-8fb25',
    authDomain: 'reciclareapp-8fb25.firebaseapp.com',
    storageBucket: 'reciclareapp-8fb25.firebasestorage.app',
    measurementId: 'G-TQ1CG0S8LJ',
  );
}
